### ISSUE TITLE
Flipping chromosome start/end in plotIdeogram

### ISSUE THREAD

**Issue by sarmapar** [PhanstielLab/plotgardener#102]
Hello! 

@toobarashid96 and I were wanting to put an ideogram along the y-axis of a square hi-c plot, but we realized that the vertical ideogram is flipped respective to the hi-c axis (see attached plot). We would like to request the addition of a "flip" parameter to plotIdeogram to allow for flipping the ideogram so the end is before/above the start. 

[example plot](https://github.com/PhanstielLab/plotgardener/files/13383166/ideogram_noflip.pdf)

**Comment by nekramer** [comment]
Those pesky Hi-C plot orientations strike again! Thank you guys for suggesting and implementing this <3
