### ISSUE TITLE
plotHicSquare rotate by 90 degrees

### ISSUE THREAD

**Issue by khayer** [PhanstielLab/plotgardener#112]
Hi,

plotgardener is a great package and thank you so much for maintaining it.

Is there a way to rotate the Hic square by 90 degrees. It seems most tools like juicebox and ucsc genome browser are displaying it more like the image on the right below.

Thank you kindly!

<img width="892" alt="image" src="https://github.com/PhanstielLab/plotgardener/assets/1101908/e204abe2-d7b3-4e22-b7e4-52b1ddcd402a">

**Comment by nekramer** [comment]
Hi Katharina,

I'm currently working on adding a parameter and feature to the `devel` branch that will allow for this! I'll check back here when it's implemented, which should be in about a week.

Best,
Nicole

**Comment by nekramer** [comment]
Hi Katharina, 

If you get the `devel` branch (version 1.9.5), you should be able to do this now! In `plotHicSquare`, I've added a `yaxisDir` parameter that will allow you to set the direction of genomic coordinate on the y-axis, which then affects the direction of the diagonal. If you would like your diagonal to go in the direction of the Hi-C map on the right, set `yaxisDir = "decrease"` for each of the Hi-C plotting calls. 

Let me know if you have any issues!
Nicole

**Comment by khayer** [comment]
Thank you kindly. It works smoothly!
