### ISSUE TITLE
generate TxDb for non-model organism 

### ISSUE THREAD

**Issue by sadikmz** [PhanstielLab/plotgardener#114]
Hi 

Following up the suggestion for non-model organism in #43, I wanted to create a TxDb for a genome of species which is not in Ensembl database.

```
# Install master branch
library(devtools)
install_github("PhanstielLab/plotgardener", ref = "master")

# Generate TxDb
library(GenomicFeatures)
txdb <- makeTxDbFromEnsembl(organism="Oncorhynchus kisutch",
                            release=NA,
                             circ_seqs=NULL,
                             server="ensembldb.ensembl.org",
                             username="anonymous", password=NULL, port=0L,
                             tx_attrib=NULL)

# Set `gene.id.column` and `display.column` to be the gene id in assembly object 
my_assembly <- assembly(
    Genome = "Okiv_V2", 
    OrgDb = NA,
    TxDb = txdb,
    gene.id.column = "ENTREZID",
    display.column = "ENTREZID"
) 
``` 

In the above example, changing the organims to _Ensete ventricosum_ would produce `no db found error` as the genome is not in Ensembl database

```
txdb <- makeTxDbFromEnsembl(organism="Ensete ventricosum",
                            release=NA,
                             circ_seqs=NULL,
                             server="ensembldb.ensembl.org",
                             username="anonymous", password=NULL, port=0L,
                             tx_attrib=NULL)

Error in .lookup_dbname(organism, release = release) : 
  no core db found in the current Ensembl release for organism "Ensete
  ventricosum"
```
 
The goal is to create a custom `assembly` object to use it in plotgardener plotting functionality. A custom `BSgenome` object was generated for the species of interest using `forgeBSgenomeDataPkg()` and I am wondring how a custom txdb and / or orgDb can be generate so it can be using for plotting.

Appreciate any suggesions

Kindly,

**Comment by nekramer** [comment]
Hey there!

Thanks for checking out `plotgardener`. Non-model organisms can indeed be tricky to work with. My best suggestion for generating a custom TxDb would be to use the `makeTxDbFromGFF` function from the `GenomicFeatures` package. This would allow you to download the .gtf or .gff annotation features file for your genome of interest (for Ensete ventricosum, looks like you can use one listed here https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=4639) and make a new `TxDb` object. You can also save this so you don't have to rebuild it every time you start a new session.

Similarly, to make a custom OrgDb, I would recommend using `makeOrgPackage` or `makeOrgPackageFromNCBI` from the `AnnotationForge` package. Here's an example for your assembly:

```
makeOrgPackageFromNCBI(version = "0.1", author = "Nicole Kramer <nekramer@live.unc.edu>", maintainer = "Nicole Kramer <nekramer@live.unc.edu>", tax_id = "4639", genus = "Ensete", species = "ventricosum")
```

Once you have these objects, you can add them and your custom BSgenome to an `assembly` object in `plotgardener`. You might have to play around with  `gene.id.column` and `display.column` depending on what IDs these objects have, but you should be able to poke around and find this info out.

I hope this helps!
Nicole

**Comment by sadikmz** [comment]
Thanks a lot for the detailed response. I used `makeTxDbFromGFF` to maket the TxDb and `makeOrgPackage` for a custom OrgDb.  It made my life easier with your suggestions.

**Comment by nekramer** [comment]
I'm so glad it helped!
