### ISSUE TITLE
Bug in plotTranscripts() labels argument

### ISSUE THREAD

**Issue by JiayuSuPKU** [PhanstielLab/plotgardener#122]
https://github.com/PhanstielLab/plotgardener/blob/7a36b36b86600f5335d7870b04a2be7e8d768688/R/plotTranscripts.R#L187

Setting 'labels' to NULL will lead to logical(0) condition and trigger Error 'argument is of length zero' in the if statement. Maybe switch to the string 'NULL' or using is.null()?

**Comment by nekramer** [comment]
Thank you so much for catching this bug! I've gone and updated this check to incorporate `is.null()` on both the release and devel branches. 

Nicole
