### ISSUE TITLE
R version 4.0.3

### ISSUE THREAD

**Issue by RegnerM2015** [PhanstielLab/plotgardener#33]
Hi @EricSDavis and @nekramer,

Is there a workaround for installing BentoBox on R version 4.0.3? When I try to install, I get the following message:

ERROR: this R is version 4.0.3, package 'BentoBox' requires R >= 4.1.0

Thanks for your help!

**Comment by nekramer** [comment]
Hi @RegnerM2015,

Unfortunately there were some updates in R 4.1.0 that ensure the full stability of the package. I don't recommend it, but if you really want to use it with R 4.0.3, you can try forking this repo, changing the R version requirement in the DESCRIPTION file, and using your own built version of the package. Hope this helps!
