### ISSUE TITLE
inverted hic matrix

### ISSUE THREAD

**Issue by chaosfang404** [PhanstielLab/plotgardener#35]
Hi,
plotgardener is a very convenient tool, but I'm wondering if you could add a feature to draw an inverted hic matrix.
such as the second track of following figure.
![master_plot_hic](https://user-images.githubusercontent.com/83016338/132276240-38ba36d7-5234-4884-842a-e33ac8b576c0.png)

**Comment by nekramer** [comment]
Thank you for this suggestion! This is a great idea and I will work on implementing it.

**Comment by nekramer** [comment]
In the most recent update (version 0.99.12) we have added this feature for `plotHicRectangle` and `plotHicTriangle`.
