### ISSUE TITLE
Custom genome

### ISSUE THREAD

**Issue by KittJonathan** [PhanstielLab/plotgardener#36]
Hi ! Thanks for your amazing work on this fantastic package ! Would it be possible to use custom genomes and cytobands for ideogram plotting ? I work on the wheat genome, and your package will be really useful for our lab. Thanks again ! Best regards, Jonathan.

**Comment by nekramer** [comment]
Thanks for checking out the package! It is indeed possible to use custom genomes and cytobands for ideogram plotting. First, I would create a custom `assembly` object with customized Bioconductor TxDb, orgDb, packages to store chromosome information about your custom genome. This can be done with the `plotgardener` `assembly()` function, and this object can be passed into the `plotIdeogram` `assembly` parameter. Custom cytoband data can be input to `plotIdeogram` with the `data` parameter as long as it is some kind of data object with the following 6 columns: seqnames, start, end, width, strand, name, and gieStain. In particular, the "gieStain" column must have character strings describing Giemsa stain values like "gneg", "gpos", etc. I recommend looking at some of our vignettes for this genome assembly customization and looking at Bioconductor AHCytoBands AnnotationHub resources to get an idea of how to format your custom cytoband data.

**Comment by KittJonathan** [comment]
Hi Nicole, thanks for your advice. Will be talking about your package in my lab for sure :-) 
Best regards,
Jonathan.
