### ISSUE TITLE
Non model Organism support

### ISSUE THREAD

**Issue by FabianGrammes** [PhanstielLab/plotgardener#43]
Hi and thanks `plotgardner` looks very interesting! I've tried to adopt the code for my work, but ran into some trouble. Maybe you can help. 

The whole `TxDb` `OrgDb` works great if you stick to model organisms (in my experience). Working with non-model organisms makes things much more of a hustle. It's fairly OK to build a `TxDb` from a .gff/gtf - as you have suggested - but building a `OrgDb` is hard work. So thus I have the following questions: 

1. Is it possible to make the`assambly` object function without a `OrgDb`? I've tried the following for Coho salmon - which does not have a (ensembl) OrgDb (I know there's a OrgDb for RefSeq, but I would like to use ensembl): 

```r
library(GenomicFeatures)
txdb <- makeTxDbFromEnsembl(organism="Oncorhynchus kisutch",
                            release=NA,
                             circ_seqs=NULL,
                             server="ensembldb.ensembl.org",
                             username="anonymous", password=NULL, port=0L,
                             tx_attrib=NULL)

my_assembly <- assembly(
  Genome = "Okiv_V2", 
  OrgDb = NA,
  TxDb = txdb
)

pageCreate(width = 7.5, height = 3.5, default.units = "inches")

genesPlot <- plotGenes(
  assembly = my_assembly,
  chromstart = 1, chromend = 30000, chrom = "LG1",
  default.units = "inches"
)
# Does not work 
```

2. What about `EnsDb` Packages? They do contain a bit more info (like gene names) then a `TxDb` is it possible to plugin a EnsDb package in the `assembly` object without the `OrgDb` ? 

3. For me, working constantly with non-model organisms, being able to skipp the TxDb / OrgDbs and beeing able to supply that information via a `GRanges` object would be easiest, so it would be great if such a feature could be added in the future. 

Thanks ! F

**Comment by nekramer** [comment]
Hi Fabian,

Thank you for this helpful feedback and these suggestions. We will work to incorporate `EnsDb` support in our `assembly` objects. However, we will not be supporting `GRanges` objects for the sake of input format consistency. 

In the meantime, it is possible to use your custom `TxDb` without an `orgDb`, so long as you do not need any kind of gene symbol data from an `orgDb` and will only be plotting labels with the gene IDs specified in your custom `TxDb`. You can specify this information with the `gene.id.column` and `display.column` parameters in `assembly()`:

```
# Install master branch
library(devtools)
install_github("PhanstielLab/plotgardener", ref = "master")

# Generate TxDb
library(GenomicFeatures)
txdb <- makeTxDbFromEnsembl(organism="Oncorhynchus kisutch",
                            release=NA,
                             circ_seqs=NULL,
                             server="ensembldb.ensembl.org",
                             username="anonymous", password=NULL, port=0L,
                             tx_attrib=NULL)

# Set `gene.id.column` and `display.column` to be the gene id in assembly object 
my_assembly <- assembly(
    Genome = "Okiv_V2", 
    OrgDb = NA,
    TxDb = txdb,
    gene.id.column = "ENTREZID",
    display.column = "ENTREZID"
)
```
This way, the function will not look for an `orgDb` package to reference for gene symbols and will only label the genes with the Entrez IDs found in the TxDb you generated.
