### ISSUE TITLE
Title not appearing in legend

### ISSUE THREAD

**Issue by EricSDavis** [PhanstielLab/plotgardener#45]
Small bug - `plotLegend()` has a `title` parameter which doesn't appear to work. We should either fix this or remove it as an option (since users can add titles with `plotText()`).

Example:
```r
plotLegend(legend = c(1, 2, 3),
           fill = c(1, 2, 3),
           title = "My title")
```
![image](https://user-images.githubusercontent.com/31807001/143946084-c68de269-97eb-472d-ad3e-dbfd02ab63de.png)

**Comment by nekramer** [comment]
This bug was fixed in RELEASE_3_14 version 1.0.7.
