### ISSUE TITLE
plotgardener issues on Windows in Bioc devel

### ISSUE THREAD

**Issue by mikelove** [PhanstielLab/plotgardener#46]
I believe plotgardener is causing issues downstream in nullranges on Windows in devel branch, here's what we see:

https://github.com/nullranges/nullranges/issues/14

plotgardener is also failing CHECK on Windows in devel with this error copied below

http://bioconductor.org/checkResults/devel/bioc-LATEST/plotgardener/riesling1-checksrc.html

```
> ## Plot y-axis label
> plotText(
+     label = "-log10(p-value)", x = 0.15, y = 1, rot = 90,
+     fontsize = 8, fontface = "bold", just = "center",
+     default.units = "inches"
+ )
Error in validGP(gp) : must specify only one of 'font' and 'fontface'
Calls: plotText ... preDraw -> preDraw.grob -> pushvpgp -> set.gpar -> validGP
Execution halted
```

I don't get it bc it seems you only use gpar here and aren't specifying font or fontface...

https://github.com/PhanstielLab/plotgardener/blob/521cefa3389c87f2102e7435e5e65bfc060c669e/R/plotText.R#L101-L104

Also weird that it only fails on Windows. Any thoughts?

**Comment by nekramer** [comment]
I was able to find the source of this error and fixed it in the devel version of `plotText`! It looks like `plotgardener` is now passing all checks in Bioc devel.

**Comment by mikelove** [comment]
Thanks Nicole! :pray:
