### ISSUE TITLE
Labeling enhancers

### ISSUE THREAD

**Issue by jamesdalg** [PhanstielLab/plotgardener#47]
I've used sushi previously, with a custom formatted data frame (chr,start,stop,gene,score,strand) using the plotGenes function to create a plot of labeled enhancers. Is it possible to label these individual elements? I've tried plotGenes (which gives labels) and plotBed (which gives custom regions, but without names). Is there a way to create a custom assembly that plotGenes will utilize? I really like the new package and all of the customization it offers in putting things exactly where you'd like them. It saves a ton of time! If somehow, one could label enhancers, or other elements, this would help greatly for enhancers, promoter regions, chromatin states, etc.  In any case, if there's some way to add a label to a bed plot or customize a gene plot with a custom assembly with only the needed elements, that would be amazing.

**Comment by dphansti** [comment]
Thanks for the post.  Glad you are finding the package useful.  I am not sure if I fully understand the question but I will try to answer.

1) For plotting enhancers, promoters, chromatin states, etc, I would recommend using plotRanges (https://phanstiellab.github.io/plotgardener/reference/plotRanges.html).  You could filter your ranges ahead of time for those that are enhancers or you could provide a vector of colors using the `fill` parameter to distinguish enhancers from other elements.

2) In the plotGenes function you can use the `geneHighlights` to provide genes to highlight with a specific color if you need to highlight some of them. You can use custom gene annotation files. This is done by creating a new assembly using the `assembly()` function.  The annotations need to be supplied in TxDb format. That new assembly object can be passed into plotGenes.

Let us know if that answers your questions.  If not, @nekramer, who wrote the package might be able to provide more explanation.
