### ISSUE TITLE
range limits on plotPairsArches

### ISSUE THREAD

**Issue by Rseq** [PhanstielLab/plotgardener#48]
Hi, 

For some unknown reason, the `range` parameter doesn't work as supposed to in `plotPairsArches()` function.
I want to plot individually different bedpe instead of concatenating different ones in the same plot.
To ensure that their signals are comparable, I wanted to force the same yscale range by using
` intervalo=c(0,203)` and then `plotPairsArches(range=intervalo,...)`. 
But it goes complete sideways, the limit is not respected and it also changes the height of some arcs (see red in the example)
Any ideas on how to ensure the behavior I'm looking for?

```
archesplot<-plotPairsArches(
  data=bedpe,chrom = chrom, chromstart = parte, chromend = ate,
  x=1.75,y=1,width = 10, height = 4,default.units = "cm",
  assembly = "hg19",archHeight = bedpe$V8, 
  style="2D",alpha=0.5,fill=bedpe$V12,linecolor="fill",clip=F #here changes plot out the window
)
annoYaxis(
  plot = archesplot,
  axisLine = TRUE, fontsize = 10
)
plotText(
  label = "PETs number", x = 0.4, y = 3, rot = 90,
  fontsize = 10, just = "center",
  default.units = "cm"
)
```
<img width="464" alt="Screenshot 2021-12-21 at 16 56 13" src="https://user-images.githubusercontent.com/32098560/146960236-5955b561-700e-41bc-8197-f25dcbab5bdc.png">

```
#bedpe1
archesplot<-plotPairsArches(
    data=bedpe[bedpe$V11==1,],chrom = chrom, chromstart = parte, chromend = ate,
    x=1.75,y=1,width = 10, height = 3,default.units = "cm",
    assembly = "hg19",archHeight = bedpe[bedpe$V11==1,8], range=intervalo,
    style="2D",alpha=1,fill=bedpe[bedpe$V11==1,12],linecolor="fill",clip=F #here changes plot out the window
  )
  annoYaxis(
    plot = archesplot,range=intervalo,
    axisLine = TRUE, fontsize = 10
  )
  plotText(
    label = "PETs number", x = 0.4, y = 2.5, rot = 90,
    fontsize = 10, just = "center",
    default.units = "cm"
  )
#bedpe 2
  archesplot2<-plotPairsArches(
    data=bedpe[bedpe$V11==2,],chrom = chrom, chromstart = parte, chromend = ate,
    x=1.75,y=4.25,width = 10, height = 3,default.units = "cm",
    assembly = "hg19",archHeight =bedpe[bedpe$V11==2,8], range=intervalo,
    style="2D",alpha=1,fill=bedpe[bedpe$V11==2,12],linecolor="fill",clip=F #here changes plot out the window
  )
  annoYaxis(
    plot = archesplot2,range=intervalo,
    axisLine = TRUE, fontsize = 10
  )
  plotText(
    label = "PETs number", x = 0.4, y = 5.75, rot = 90,
    fontsize = 10, just = "center",
    default.units = "cm"
  )
#bedpe 3
  archesplot3<-plotPairsArches(
    data=bedpe[bedpe$V11==3,],chrom = chrom, chromstart = parte, chromend = ate,
    x=1.75,y=7.5,width = 10, height = 3,default.units = "cm",
    assembly = "hg19",archHeight = bedpe[bedpe$V11==3,8], range=intervalo,
    style="2D",alpha=1,fill=bedpe[bedpe$V11==3,12],linecolor="fill",clip=F #here changes plot out the window
  )
  annoYaxis(
    plot = archesplot3,range=intervalo,
    axisLine = TRUE, fontsize = 10
  )
  plotText(
    label = "PETs number", x = 0.4, y = 9, rot = 90,
    fontsize = 10, just = "center",
    default.units = "cm"
  )
```
<img width="461" alt="Screenshot 2021-12-21 at 17 00 09" src="https://user-images.githubusercontent.com/32098560/146960668-0ec36cb2-b11f-4ae4-8695-e74b71643d6f.png">

thank you for your time,

**Comment by nekramer** [comment]
Thanks for your post! Currently `plotPairsArches` doesn't have a `range` parameter, so the function is just ignoring any range you set and scaling the arch heights relative to the entire range. I will be adding a `range` parameter and will come back and comment on this issue when that is resolved.

For `archHeight`, it's possible that the column you are specifying to set the heights isn't numeric. Would you be able to include the data you are using here?

Best,
Nicole

**Comment by Rseq** [comment]
Thanks you for your reply. 

The stranger part to me and that I really would like to understand and fix is why it changes the height of some arcs (see red in the example) when I use separated plots since they are all from the same table.
How can I correct this behavior?

Unfortunately, I'm unable to share the data itself due to some rules.
Would this reply your question?

```
> is.numeric(bedpe $V8) 
[1] TRUE 
> class(bedpe) 
[1] "data.frame"

```

**Comment by nekramer** [comment]
I have now added a `range` parameter that should allow you to specify the same range for your separate plots. I also found a tiny bug that seemed to be scaling the heights incorrectly, so I have fixed that as well. Please let me know if this solves your problem!

**Comment by Rseq** [comment]
Hi Nicole,
Many thanks for your reply and for including this parameter. I updated via Github. 
I think it is almost there. The `range` parameter is working as expected indeed. 
However, I think there is some normalization step going on that may be interfering on the height of some pairs in the selected window.
Below you can observe the difference between plotting all loops together (A) vs individually (B) using the exact same parameters. I would expect that height would be kept the same regardless of the different pairs in the same window. In my dataset each color represent pairs from different categories.

<img width="783" alt="Screen Shot 2022-01-17 at 23 19 33" src="https://user-images.githubusercontent.com/32098560/149843060-f946720c-7c2b-4219-91b6-9e9980a376d2.png">

**Comment by nekramer** [comment]
This is odd behavior indeed! There is some normalization required for the math of plotting the curves, but this normalization occurs relative to the range of the plotted region and should maintain the same heights if each plot's `range` is the same. I have checked the logic for this and everything seems to be working as expected. Here is an example where I observe the appropriate behavior:
![arches-1](https://user-images.githubusercontent.com/44094608/149849100-352af156-fd58-4b6d-afe6-dcbf81c455bd.png)
Again, it's a bit difficult for me to see why it would be re-scaling the heights of your data and not mine. Without seeing the data and all of the code, these are my suggestions of what to check: the overall height of the plot, the archHeights are numerics, ensuring that the vector of archHeights actually corresponds to your data in the proper order.

**Comment by Rseq** [comment]
Thank you for your reply. I sent you the data via email.  
This is the script I'm using:

```
#### parameters ####

bedpe=read.table("HiChIP_example_chr19.bedpe")
chrom='chr19'
parte=38874917
ate=40040338
intervalo=c(0,50)

#### Overall plot ####

pageCreate(
  width = 12, height = 14,default.units="cm",
  showGuides = F, xgrid = 0, ygrid = 0
) 
#bedpe
archesplot<-plotPairsArches(
  data=bedpe,chrom = chrom, chromstart = parte, chromend = ate, range=intervalo,
  x=1.75,y=1,width = 10, height = 4,default.units = "cm",
  assembly = "hg19",archHeight = bedpe$V8, alpha=1,
  style="2D",fill=bedpe$V12,linecolor="fill",clip=F #here changes plot out the window
)
annoYaxis(
  plot = archesplot,
  axisLine = TRUE, fontsize = 10
)
plotText(
  label = "PETs number", x = 0.4, y = 3, rot = 90,
  fontsize = 10, just = "center",
  default.units = "cm"
)

#### Individual plots ####

pageCreate(
    width = 12, height = 17,default.units="cm",
    showGuides = F, xgrid = 0, ygrid = 0
  ) 
  #bedpe
  archesplot<-plotPairsArches(
    data=bedpe[bedpe$V11==1,],chrom = chrom, chromstart = parte, chromend = ate,
    x=1.75,y=1,width = 10, height = 3,default.units = "cm",
    assembly = "hg19",archHeight = bedpe$V8, range=intervalo,
    style="2D",alpha=1,fill=bedpe[bedpe$V11==1,12],linecolor="fill",clip=F #here changes plot out the window
  )
  annoYaxis(
    plot = archesplot,
    axisLine = TRUE, fontsize = 10
  )
  plotText(
    label = "PETs number", x = 0.4, y = 2.5, rot = 90,
    fontsize = 10, just = "center",
    default.units = "cm"
  )
  
  #bedpe 2
  archesplot2<-plotPairsArches(
    data=bedpe[bedpe$V11==2,],chrom = chrom, chromstart = parte, chromend = ate,
    x=1.75,y=4.25,width = 10, height = 3,default.units = "cm",
    assembly = "hg19",archHeight = bedpe$V8, range=intervalo,
    style="2D",alpha=1,fill=bedpe[bedpe$V11==2,12],linecolor="fill",clip=F #here changes plot out the window
  )
  annoYaxis(
    plot = archesplot2,
    axisLine = TRUE, fontsize = 10
  )
  plotText(
    label = "PETs number", x = 0.4, y = 5.75, rot = 90,
    fontsize = 10, just = "center",
    default.units = "cm"
  )
  
  #bedpe 3
  archesplot3<-plotPairsArches(
    data=bedpe[bedpe$V11==3,],chrom = chrom, chromstart = parte, chromend = ate,
    x=1.75,y=7.5,width = 10, height = 3,default.units = "cm",
    assembly = "hg19",archHeight = bedpe$V8, range=intervalo,
    style="2D",alpha=1,fill=bedpe[bedpe$V11==3,12],linecolor="fill",clip=F #here changes plot out the window
  )
  annoYaxis(
    plot = archesplot3,
    axisLine = TRUE, fontsize = 10
  )
  plotText(
    label = "PETs number", x = 0.4, y = 9, rot = 90,
    fontsize = 10, just = "center",
    default.units = "cm"
  )

```

**Comment by Rseq** [comment]
I think that part of the issue is about subset. But, I couldn't understand why normalization would reflect this differently. 

Since I changed the window region from the previous examples to have less pairs, below is the output from the #### Overall plot #### section:

<img width="447" alt="Screen Shot 2022-01-18 at 12 51 38" src="https://user-images.githubusercontent.com/32098560/149932854-e76d5592-9b16-49c6-b6df-40a0e3c29764.png">

This is the output from #### Individual plots #### section:

<img width="452" alt="Screen Shot 2022-01-18 at 12 56 53" src="https://user-images.githubusercontent.com/32098560/149933167-0797740c-3b01-45ca-aac4-2899405e1404.png">

This is the output from #### Individual plots #### section if I change `archHeight = bedpe$V8` for `archHeight = bedpe[bedpe$V11==1,8]` `archHeight = bedpe[bedpe$V11==2,8]` `archHeight = bedpe[bedpe$V11==3,8]` to correspond accordingly to `data=bedpe[bedpe$V11==NUMBER,]`

<img width="460" alt="Screen Shot 2022-01-18 at 12 48 16" src="https://user-images.githubusercontent.com/32098560/149933613-0e6746c8-12fa-494d-a307-5733d3b90ad7.png">

Still using the parameters 

```
#### parameters ####

bedpe=read.table("HiChIP_example_chr19.bedpe")
chrom='chr19'
parte=38874917
ate=40040338
intervalo=c(0,50)

```

**Comment by nekramer** [comment]
I think I understand what is happening. The `archHeight` parameter takes a vector, but does not parse this vector as corresponding to a column in the dataframe. Thus, if you are inputting a subset of your data but not changing the input of `archHeight`, it is going to grab the heights from the beginning of the vector and then they might no longer correspond to the rows of data you intend them to. The section of code where you change the individual plots: 

> `archHeight = bedpe[bedpe$V11==1,8]` `archHeight = bedpe[bedpe$V11==2,8]` `archHeight = bedpe[bedpe$V11==3,8]` to correspond accordingly to `data=bedpe[bedpe$V11==NUMBER,]` 

should be correct and should keep the heights as you expect. I apologize if this is confusing, and I am willing to take feedback on the implementation of this feature.

Also, please note that since the individual plots are slightly smaller in height than the overall plot, this will visually skew the appearance of the heights.

**Comment by Rseq** [comment]
I understood your point, but there is something still off. A similar behavior can be observed if I use the same parameters, one plot but I focus in different regions.  I'm leaving a marker below (RNA) to pinpoint the region I'm focusing in. As you can see, the difference of dark blue pair to the red pair on top of the marker changes according to window (start/parte, end/ate) being used. 

overall script

pageCreate(
  width = 12, height = 14,default.units="cm",
  showGuides = F, xgrid = 0, ygrid = 0
) 
#bedpe
archesplot<-plotPairsArches(
  data=bedpe,chrom = chrom, chromstart = parte, chromend = ate, range=intervalo,
  x=1.75,y=1,width = 10, height = 4,default.units = "cm",
  assembly = "hg19",archHeight = bedpe[,8], alpha=1,
  style="2D",fill= bedpe[,12],linecolor="fill",clip=F #here changes plot out the window
)
annoYaxis(
  plot = archesplot,
  axisLine = TRUE, fontsize = 10
)
plotText(
  label = "PETs number", x = 0.4, y = 3, rot = 90,
  fontsize = 10, just = "center",
  default.units = "cm"
)
#bed RNA
plotRanges(
  data = RNA, chrom = chrom, chromstart = parte, chromend = ate,
  assembly = "hg19",
  x=1.75, y =5.25, width = 10, height = 0.5, default.units = "cm",
  linecolor="grey0",fill="grey0",
  strandSplit=F,collapse=T
)
plotText(
  label = "RNA", x = 0.05, y = 5.5, rot=0,
  fontsize = 10, just = "left",
  default.units = "cm"
)

The zoom in changes and its outputs:
```
chrom='chr19'
parte=38874917
ate=40040338
```
<img width="577" alt="Screen Shot 2022-01-18 at 18 16 24" src="https://user-images.githubusercontent.com/32098560/149986227-9051fd94-2b9b-4ef5-90de-366d85220c56.png">

```
chrom='chr19'
parte=39595857
ate=39931640
```
<img width="588" alt="Screen Shot 2022-01-18 at 18 15 19" src="https://user-images.githubusercontent.com/32098560/149987144-1404a595-1efd-4143-b681-347d400b208b.png">

```
chrom='chr19'
parte=39830000
ate=39969193
```
<img width="589" alt="Screen Shot 2022-01-18 at 18 16 45" src="https://user-images.githubusercontent.com/32098560/149987630-95301110-3b25-4b0b-aef7-c3506db38f18.png">

It feels like that there is a subset that changes the behavior of `archHeight` in different ways. Is it possible to remove the normalization? If not, why is impacting the results in such way?

**Comment by nekramer** [comment]
Yes, I see what you are saying. What's most likely happening is that the input vector of `archHeights` isn't actually corresponding to the subsetted data that will be plotted in that region. 

To more easily achieve the behavior you are looking for, I have added an option to `archHeight` to specify the column name in your input data to use as the heights. This way, the data and heights will be subsetted together and thus should remain consistent. To use this, you would use something like this:
`archesplot<-plotPairsArches(
  data=bedpe,chrom = chrom, chromstart = parte, chromend = ate, range=intervalo,
  x=1.75,y=1,width = 10, height = 4,default.units = "cm",
  assembly = "hg19",archHeight = "V8", alpha=1,
  style="2D",fill= bedpe[,12],linecolor="fill",clip=F #here changes plot out the window
)` where "V8" is the name of the column with your heights. Give this a try and let me know if it works appropriately.

**Comment by Rseq** [comment]
Working perfectly well, even if I split the plots. Perfect!
Many many thanks for your wonderful support. 
I really appreciated the package and your help. 
Great work!
