### ISSUE TITLE
annoDomains( ) in plotHicRectangle( ) vs plotHicTriangle( )

### ISSUE THREAD

**Issue by Rseq** [PhanstielLab/plotgardener#49]
Hi all,

I'm trying to plot some HiC dataset and I found a funny behaviour between  `plotHicRectangle( ) ` vs `plotHicTriangle( ) `when using `annoDomains( )`.
As one can see on the code below + the outcome, the annotations from `annoDomains( )` change coordinates between `plotHicRectangle( )` vs `plotHicTriangle( )`. Am I thinking wrongly to expect that they should not be displaced in  `plotHicTriangle( )`? 
The `plotHicRectangle( ) annoDomains( )` behaves close to what I see in juicerbox.

```
chrom="chr17"
parte=8000000
ate=14000000

pageCreate(
  width = 12, height = 14,default.units="cm",
  showGuides = F, xgrid = 0, ygrid = 0
) 
#hic
hicPlot<-plotHicRectangle(
  data = HiC_data, resolution = 25000, #same resolution as in readHic()
  chrom = chrom, chromstart = parte, chromend = ate,
  assembly = "hg19", bg = NA,norm = "NONE", palette = colorRampPalette(c(cpaper[1],cpaper[4])),
  x=1.75,y=1,width = 10, height = 4,default.units = "cm",
)
annoDomains(
  plot = hicPlot, data = HiC_data_TAD,
  chrom = chrom, chromstart = parte, chromend = ate, #adding here just to ensure
  x=1.75,y=1,width = 10, #adding here just to ensure
  assembly = "hg19", linecolor = cpaper[2],lwd=2
)
## Annotate heatmap legend
annoHeatmapLegend(
  plot = hicPlot,assembly = "hg19",
  x = 10, y =1, width = 0.12, height = 1.2,
  default.units = "cm"
)

```

<img width="393" alt="Screen Shot 2022-01-12 at 00 27 03" src="https://user-images.githubusercontent.com/32098560/149038171-eb44fe8b-b145-494a-8fc1-bd505a3fa84a.png">

```
chrom="chr17"
parte=8000000
ate=14000000

pageCreate(
  width = 12, height = 14,default.units="cm",
  showGuides = F, xgrid = 0, ygrid = 0
) 
#hic
hicPlot<-plotHicTriangle(
  data = HiC_data, resolution = 25000, #same resolution as in readHic()
  chrom = chrom, chromstart = parte, chromend = ate,
  assembly = "hg19", bg = NA,norm = "NONE", palette = colorRampPalette(c(cpaper[1],cpaper[4])),
  x=1.75,y=1,width = 10, height = 4,default.units = "cm",
)
annoDomains(
  plot = hicPlot, data = HiC_data_TAD,
  chrom = chrom, chromstart = parte, chromend = ate, #adding here just to ensure
  x=1.75,y=1,width = 10, #adding here just to ensure
  assembly = "hg19", linecolor = cpaper[2],lwd=2
)
## Annotate heatmap legend
annoHeatmapLegend(
  plot = hicPlot,assembly = "hg19",
  x = 10, y =1, width = 0.12, height = 1.2,
  default.units = "cm"
)

```
<img width="389" alt="Screen Shot 2022-01-12 at 00 26 15" src="https://user-images.githubusercontent.com/32098560/149038207-d4f9ded5-1449-476b-9162-42198cd36db0.png">

Another example of a different region:
<img width="387" alt="Screen Shot 2022-01-12 at 11 24 45" src="https://user-images.githubusercontent.com/32098560/149122966-12fd433a-8528-40e7-90a8-4d7ffd0238c1.png">

As you can see, the annotation and the Heatmap is miss allocated

**Comment by nekramer** [comment]
Thank you for finding this bug. It actually appeared that the limits were wrong when annotating domains in for a plot made with `plotRectangleHic`. Upon unit testing, domains appear to be correctly annotating square, triangle, and rectangle Hi-C plots.

**Comment by Rseq** [comment]
Many thanks for your support. It is working nicely. Closing here this thread
