### ISSUE TITLE
clip parameter in `plotPairsArches( )`

### ISSUE THREAD

**Issue by Rseq** [PhanstielLab/plotgardener#50]
HI all,

Sorry for the amount of questions here, but I'm trying to move all the lab's data to plotgardener.
This time I have observed an strange behavior in the `clip` parameter in `plotPairsArches( )`
If I understood correctly, `clip=FALSE` would allow plotting all arches even when part of the arches are outside of the window region. Correct? 
Strangely, it acts as supposed for the right side of the graph, but not for the left one. 
In the example below I should be able to see one extra blue arch that comes from left size. 

Any ideas how to fix it?

```
head(bedpe)

   V1      V2      V3   V4      V5      V6                      V7 V8           V9 V10 V11
1 chr1 1281913 1286950 chr1 1396138 1400747 inter1  5 9.553711e-09   .   1
2 chr1 1309910 1312529 chr1 1374713 1377761 inter2 10 5.077840e-15   .   1
3 chr1 1712842 1715416 chr1 2013909 2016219 inter3  2 6.126462e-04   .   1
4 chr1 1927944 1930266 chr1 1943167 1945312 inter4 14 6.854220e-03   .   1
5 chr1 1934059 1937810 chr1 1940353 1941639 inter5 19 4.856376e-06   .   1
6 chr1 6319851 6322042 chr1 6518142 6520672 inter6 12 0.000000e+00   .   1

chrom='chr19'
parte=39610427
ate=39932467

pageCreate(
  width = 12, height = 14,default.units="cm",
  showGuides = F, xgrid = 0, ygrid = 0
) 
#bedpe
archesplot<-plotPairsArches(
  data=bedpe,chrom = chrom, chromstart = parte, chromend = ate,
  x=1.75,y=1,width = 10, height = 4,default.units = "cm",
  assembly = "hg19",archHeight = bedpe$V8, alpha=1,
  style="2D",fill=bedpe$V12,linecolor="fill",clip=F #here changes plot out the window
)
annoYaxis(
  plot = archesplot,
  axisLine = TRUE, fontsize = 10
)
plotText(
  label = "PETs number", x = 0.4, y = 3, rot = 90,
  fontsize = 10, just = "center",
  default.units = "cm"
)
```

<img width="591" alt="Screen Shot 2022-01-13 at 14 38 37" src="https://user-images.githubusercontent.com/32098560/149340651-5568a516-5e29-425d-b640-bd4eb22711e4.png">

Same code but zooming in
```
parte=39830000
ate=39969193
chrom='chr19'

```

<img width="590" alt="Screen Shot 2022-01-13 at 14 43 41" src="https://user-images.githubusercontent.com/32098560/149341228-bea4a4a9-341e-4df2-8a76-8f694fc042ea.png">

**Comment by nekramer** [comment]
Again, thank you for finding this behavior! Indeed, you are correct in your understanding of what the `clip` parameter was supposed to do. I have now updated the subsetting logic to include arches that overlap the plotted range (using Bioconductor `IRanges` `subsetByOverlaps`). This should now allow any arches that fall in the range, regardless of if they have an anchor there, to be plotted. Please let me know if this solves your problem.

**Comment by Rseq** [comment]
Hi Nicole,
Thank you again for adjusting it. I really appreciate your help.
I uploaded to the latest version as suggested.
I think the new approach sorted out the issue from pairs that have one anchor outside of the left part of window.
However, I think this also introduced a behavior that shows any pairs on the window even when there is no anchor within the limits of the window - it just pass thru. Please see the example below (arrow). 
Is there a way to include an option to just show pairs that has at least one anchor within the window independent of which side the other anchor is?


<img width="531" alt="Screen Shot 2022-01-17 at 23 42 49" src="https://user-images.githubusercontent.com/32098560/149844825-900abc38-257e-45fb-bf00-9a3e0ad5d3b6.png">

**Comment by nekramer** [comment]
Yes, I have just added an additional parameter `clip.noAnchor` which you can set to `FALSE` and will only clip those arches that don't have anchors in the region. If you set `clip = FALSE` and `clip.noAnchor = TRUE`, you should be able to achieve the behavior you're looking for.

**Comment by Rseq** [comment]
It is working working very well. Thank you.
