### ISSUE TITLE
Potential issue plotting tracks with negative values

### ISSUE THREAD

**Issue by adippolito12** [PhanstielLab/plotgardener#52]
Hello,

I seem to have come across an issue when calling plotSignal to plot a bigWig file with negative scores (with negData=T). I get the following error:

Error in signal2[, "score2"] : subscript out of bounds

When I manually remove the negative values, it seems to resolve the issue. I couldn't find the "score2" column assignment in the code. I assumed it may have been an error and changed "score2" on line 418 in plotSignal.R to "score" and that seemed to resolve the issue as well, but I'm not sure if that's kosher.

Thanks,
Tony

**Comment by nekramer** [comment]
Hi Tony,

Thank you for catching this! This was indeed a typo, so I have gone and fixed this in the latest version. Please let me know if you have any additional issues.

Nicole
