### ISSUE TITLE
Is there a way to highlight transcripts?

### ISSUE THREAD

**Issue by davhum** [PhanstielLab/plotgardener#54]
Hi team, 

The highlight feature in plotGenes is fantastic. Wondering if there is a way to do this for plotTranscripts? I cannot see anything in the documentation. If this doesn't exist perhaps it is something you might consider in adding in the future.

Thanks for a great package.

**Comment by nekramer** [comment]
Hi David,

Thanks for checking out the package! Right now we don't have a feature where we allow highlighting of transcripts, but we'd definitely consider adding something like this to the next version. I'd be happy to take suggestions on how you'd like to see this implemented. 

Best,
Nicole
