### ISSUE TITLE
Color Ideogram bands

### ISSUE THREAD

**Issue by mauerjh** [PhanstielLab/plotgardener#55]
Hello! I've been using plotgardener recently and finding it great! 
I'd like to know if it's possible to change band colors in chromosome ideograms and how to do so (in the default ones, the centromere is colored green and some chroms have colored blue bands, I'd like to modify these colors). Thanks!

**Comment by nekramer** [comment]
Hi Jessica,

Glad to hear you're liking plotgardener! There is a new feature in the devel version (master branch, version 1.1.17) that allows for custom cytoband coloring in chromosome ideograms by specifying a vector of colors to `fill`. You must supply the appropriate number of colors for how many different types of stains there are for that particular genome assembly. This vector can be unnamed, which will then assign the colors based on the order of the levels of the stain types, or it can be named, where each specific stain type can be associated with a specific color. So for example, the hg19 stains include gneg, gpos25, gpos50, gpos75, gpos100, acen, gvar, and stalk, so you would pass a vector of colors of length 8. If you're curious to see with each function call how exactly we're assigning colors, you can now look inside the `ideogram` plot object that is returned and look inside the `colors` slot to get each gieStain/color pair.

I hope this helps! Please let me know if you have any issues.

Best,
Nicole

**Comment by nekramer** [comment]
Just wanted to follow up on this issue and check if it has been resolved. Were you able to successfully change the chromosome ideogram band colors with the new update?
