### ISSUE TITLE
Inverting domain annotations and clipping plotHicTriangle

### ISSUE THREAD

**Issue by benayang** [PhanstielLab/plotgardener#56]
Thank you for developing this package! I'm using plotgardener v.1.0.17 in R v.4.1.2 and was wondering if it's possible to a) invert domain annotation triangles and b) set the maximum distance shown in plotHiCTriangle.

I'm interested in comparing contact domains between Hi-C maps using plotHiCTriangle. Adding "flip=T" for the bottom triangle successfully inverts the Hi-C map, but domains plotted using annoDomains aren't inverted. My code and the resulting plot are shown below. It would also be great I could limit the height of each triangle to focus on the Hi-C counts for each domain. Thanks!

```
params = pgParams(chrom = chrom, chromstart = chromstart, chromend = chromend,
                   x = 0.5, width = 3, assembly = "mm10")

pageCreate(width = 4, height = 4, default.units = "inches")

young_hicPlot = plotHicTriangle(
  data = young_mat_log1p,
  resolution = 40e3,
  palette = colorRampPalette(rev(brewer.pal(n = 9, "RdBu"))),
  zrange = c(0,4),
  bg = "white",
  params = params,
  y = 0.5, height = 1.5,
  just = c("left", "top"), default.units = "inches"
)
young_domainsTriangle = annoDomains(plot=young_hicPlot, data=young.domain.triangles, params=params)

aged_hicPlot = plotHicTriangle(
  data = aged_mat_log1p,
  resolution = 40e3,
  palette = colorRampPalette(rev(brewer.pal(n = 9, "RdBu"))),
  zrange = c(0,4),
  bg = "white",
  flip = T,
  params = params,
  y = "0b", width = 3, height = 1.5,
  just = c("left", "top"), default.units = "inches"
)
aged_domainsTriangle = annoDomains(plot=aged_hicPlot, data=aged.domain.triangles, params=params)
```

![image](https://user-images.githubusercontent.com/32141359/161856149-03f37da9-ddfe-4358-8e7f-802bcca9d8a2.png)

**Comment by nekramer** [comment]
Hi Benjamin,

Thanks for checking out plotgardener! In the newest development version (master branch, v.1.1.18), you should now be able to appropriately label the domains of your flipped triangle Hi-C plot. Give that a try and let me know if you have any issues.

As for limiting the height of each triangle, if you make the `height` parameter smaller than what the actual height would be for a triangle with the given width, the triangle will be clipped at the top to a trapezoid shape. For example, if you change `height = 1.5` to `height = 1`, the tops of the triangles should be clipped off. If you're looking for a slightly different shape/way to do this, I recommend checking out `plotHicRectangle`. I hope this helps!

Best,
Nicole

**Comment by benayang** [comment]
Hi Nicole,

Thanks for the update, it's working great now! For plotting with `plotHicRectangle`, is it possible to independently assign colors to annotated domains? It would be great to be able to highlight rearranged domains.

Best,
Ben

**Comment by nekramer** [comment]
Hi Ben,

Are you trying to assign colors to different domains within the Hi-C maps themselves or assign colors to the domain annotations? If the former, it is not possible to color the same Hi-C map with different color palettes. If the latter, if you know how to separate the non-rearranged from the rearranged domains, you can annotate them in separate function calls and change the colors of the lines with the `linecolor` parameter.

Best,
Nicole
