### ISSUE TITLE
plotSignal help/error?

### ISSUE THREAD

**Issue by jaclyn-marie** [PhanstielLab/plotgardener#57]
Hi!

Thank you for making plotgardener! It has been working really smoothly so far, however I am having some trouble with plotSignal. I imported eigenvectors as a txt file (adding +1 to the start position to avoid error), and I am trying to plot the signal but I keep getting:

"Error: Cannot find associated `score` column in data."

> #loaded data using
pancAB <- as.data.frame(read.table("path...", 
                                    header = FALSE, sep="\t", stringsAsFactors=FALSE))

> tail(pancAB)      #score to plot is in V4
       V1        V2        V3          V4
425 chr14 106000001 106250000 0.047127906
426 chr14 106250001 106500000 0.028195301
427 chr14 106500001 106750000 0.011045995
428 chr14 106750001 107000000 0.007308548
429 chr14 107000001 107250000 0.005714178
430 chr14 107250001 107500000 0.011754298

> #attempting to plot the data 
plotSignal(
  pancAB,
  negData = TRUE,
  assembly = "hg19",
  linecolor = "grey",
  fill = c("yellow", "blue"),
  ymax = 1,
  baseline = TRUE,
  baseline.color = "grey",
  baseline.lwd = 1,
  orientation = "h",
  x = 1,
  y = 1.5,
  width = 3,
  height = 0.5,
  just = c("left", "top"),
  default.units = "inches",
  draw = TRUE,
  params = params_a,
)

Is this a problem with the format/column number in my dataset? I am running R 4.1.3 on windows through Rstudio. 
Thanks in advance for any tips!

Sincerely,
Jaclyn

**Comment by nekramer** [comment]
Hi Jaclyn,

Thanks for checking out plotgardener!! That error is popping up because the columns of your dataframe need to be named with the appropriate BED column names. In your case, it looks like you would need to to do `colnames(pancAB) <- c("chrom", "start", "end", "score")`. Give this a try and let me know if you have any other issues.

Best,
Nicole

**Comment by jaclyn-marie** [comment]
Nicole,

Thank you for the speedy reply!!! That solved the error, my apologies for not checking that.

Jaclyn
