### ISSUE TITLE
Parameter to scale signals

### ISSUE THREAD

**Issue by climouse** [PhanstielLab/plotgardener#59]
Hi team,
Very nice package! Definitely my new goto package for plotting genome tracks, that's a great contribution! Is there a way to introduce a scaling parameter for a bigwig signal track? It would be useful for example to normalize for sequencing depth without having to create a normalized bigwig. 

Also, the negData is very convenient for plotting stranded signals, but is there a way to allow the second file to be a bigwig with negative values (rather than only allowing a bigwig with positive values and flipping the y axis)? That would perhaps be more consistent with IGV, where to represent stranded signal it is common to overlay a plusStrand.bw and minusStrand.bw, where the plusStrand/minusStrand.bw are positive/negative values bigwigs, respectively.

Thanks!

**Comment by climouse** [comment]
Thank Nicole! Got it, it makes sense that you want to keep the data manipulation out of the package. Preloading the bigwig to directly scale the score values is easy enough and more general. I hadn't noticed this function but it's perfect.
Another couple of suggestions in terms of visualization options, if I may are 

1)  it would be great to have the option for plotSignals to include a y axis with tick marks showing the min/max of the range (rather than having the range displayed as [min-max]). In my opinion a y-axis makes for nicer looking figures.
2)  it would also help to have a simple "label" argument for plotSignals to label the track. I know this can currently be done with plotText but since this is such a common scenario, it would shorten the code a bit to handle the track labeling with a single parameter. Ideally the label could be positioned at the top left (where [min/max] is) or to the left of the track. 

Best,

**Comment by nekramer** [comment]
Thank you for these suggestions! For adding a y-axis, I would actually recommend using `annoYaxis` as shown in this reprex:
``` r
library(plotgardenerData)
data("IMR90_ChIP_H3K27ac_signal")
data("GM12878_ChIP_H3K27ac_signal")

## Create a page
pageCreate(width = 7.5, height = 2.1, default.units = "inches", 
           showGuides = FALSE)

## Define region
region <- pgParams(
    chrom = "chr21",
    chromstart = 28000000, chromend = 30300000,
    assembly = "hg19",
    range = c(0, 45)
)

## Plot and place signal plots
signal1 <- plotSignal(
    data = IMR90_ChIP_H3K27ac_signal, params = region,
    x = 0.5, y = 0.25, width = 6.5, height = 0.65,
    just = c("left", "top"), default.units = "inches"
)
#> signal[signal1]

## Add y-axis, without axis line
annoYaxis(plot = signal1, at = c(0, 45))
```

![](https://i.imgur.com/lSXaCEU.png)

    #> yaxis[yaxis1]

    signal2 <- plotSignal(
        data = GM12878_ChIP_H3K27ac_signal, params = region,
        linecolor = "#7ecdbb",
        x = 0.5, y = 1.1, width = 6.5, height = 0.65,
        just = c("left", "top"), default.units = "inches"
    )
    #> signal[signal2]

    ## Add y-axis, with axis line
    annoYaxis(plot = signal2, at = c(0, 45), axisLine = TRUE)
    #> yaxis[yaxis2]

    ## Plot genome label
    plotGenomeLabel(
        chrom = "chr21",
        chromstart = 28000000, chromend = 30300000,
        assembly = "hg19",
        x = 0.5, y = 1.78, length = 6.5,
        default.units = "inches"
    )
    #> genomeLabel[genomeLabel1]

    ## Add text labels
    plotText(
        label = "IMR90", fonsize = 10, fontcolor = "#37a7db",
        x = 0.58, y = 0.25, just = c("left", "top"),
        default.units = "inches"
    )
    #> text[text1]
    plotText(
        label = "GM12878", fonsize = 10, fontcolor = "#7ecdbb",
        x = 0.58, y = 1.1, just = c("left", "top"),
        default.units = "inches"
    )
    #> text[text2]

![](https://i.imgur.com/uUCOt7Q.png)

<sup>Created on 2022-05-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I add the range for ticks manually here, but please note that you can also find the range from a `signal` object returned.

I will also work on adding a more convenient label option!

Best,
Nicole

**Comment by climouse** [comment]
Fantastic, that looks really nice, thanks Nicole!

**Comment by nekramer** [comment]
I've gone ahead and added those feature updates to the `master` branch, as referenced above. You should now be able to use data with negative values, and I've added a convenience label parameter for quick text labeling. Check out the commits above and let me know if you have any issues! Thanks again for the suggestions!

Best,
Nicole
