### ISSUE TITLE
plot .mcool format

### ISSUE THREAD

**Issue by tamerbio** [PhanstielLab/plotgardener#66]
Dear Plotgardeners,
I would like to express my deep thanks for such an extraordinary package that made our life far easy. thanks to everyone who contributed to this great work.
one more thing, could you please implement a function to use .mcool as well?
many many thanks
Tamer

**Comment by jiangshan529** [comment]
> Thank you for checking out plotgardener! A function to use .mcool files is definitely something we're hoping to implement soon. I'll keep this issue up and labeled until we have this going.
> 
> Thanks for the feedback, Nicole

Hi, Nicole,

I am using this tool to read a hic file as input "readHic("C:/projects/hic/hic/public_data/hela_s3/Hela_s3_microC_4DNFIVA2IV88.hic", chrom="1", chromstart = 72400000, chromend = 72405000 )", however, it reports this error: Warning: No data found in region. Suggestions: check that chromosome names match genome assembly; check region; check available resolutions with `strawr::readHicBpResolutions()`.. Am I reading the input in a wrong way? Thanks!
