### ISSUE TITLE
cannot install plotgardener on an M1 Mac

### ISSUE THREAD

**Issue by a-g-robertson** [PhanstielLab/plotgardener#68]
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rhtslib’
ERROR: dependency ‘Rhtslib’ is not available for package ‘Rsamtools’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rsamtools’
ERROR: dependency ‘Rsamtools’ is not available for package ‘GenomicAlignments’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/GenomicAlignments’
ERROR: dependencies ‘Rsamtools’, ‘GenomicAlignments’ are not available for package ‘rtracklayer’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/rtracklayer’
ERROR: dependencies ‘rtracklayer’, ‘GenomicAlignments’, ‘Rsamtools’ are not available for package ‘plyranges’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/plyranges’
ERROR: dependency ‘plyranges’ is not available for package ‘plotgardener’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/plotgardener’
* ...
Warning messages:
1: In install.packages(...) :
  installation of package ‘Rhtslib’ had non-zero exit status
2: In install.packages(...) :
  installation of package ‘Rsamtools’ had non-zero exit status
3: In install.packages(...) :
  installation of package ‘GenomicAlignments’ had non-zero exit status
4: In install.packages(...) :
  installation of package ‘rtracklayer’ had non-zero exit status
5: In install.packages(...) :
  installation of package ‘plyranges’ had non-zero exit status
6: In install.packages(...) :
  installation of package ‘plotgardener’ had non-zero exit status

I understand that these are dependencies, and it's not your responsibility to deal with them.

**Comment by a-g-robertson** [comment]
Thanks, I found I'd been using BiocManager v4.15. I've updated to v4.16, and am re-installing packages. When this is done, I'll retry installing plotgardener.

**Comment by a-g-robertson** [comment]
After updating BiocManager to v4.16 (R arm64 v4.2.1, latest RStudio v2022.07.2 Build 576, macOS v12.6.1), and reinstalling all packages, I've just walked through the plotgardener vignette, apparently successfully, on an M1 Mac laptop. Thank you for your help.

**Comment by nekramer** [comment]
Great, I'm glad to hear it's working!
