### ISSUE TITLE
`annoPixels()` does not annotate all pixels present in a rectangle HiC plot

### ISSUE THREAD

**Issue by sarmapar** [PhanstielLab/plotgardener#69]
Firstly, love the package & it has been amazing to use so far!!

One issue I've run into--
When using `annoPixels()` on a rectangle HiC plot, only the pixels with both chromstart and chromend within the x-axis range are annotated instead of all pixels displayed in the plot. 

An example created by modifying the first example of `annoPixels()`:
```{r}

library(plotgardenerData)
data("IMR90_HiC_10kb")
data("IMR90_DNAloops_pairs")

## Create page
pageCreate(width = 4.5, height = 4, default.units = "inches")

## Plot and place a rectangle Hi-C plot
## zoomed-in to fill the rectangle 
hicPlot <- plotHicRectangle(
  data = IMR90_HiC_10kb, resolution = 10000,
  zrange = c(0, 70),
  chrom = "chr21",
  chromstart = 28800000, chromend = 29700000,
  assembly = "hg19",
  x = 0.5, y = 0.5, width = 3, height = 2,
  just = c("left", "top"),
  default.units = "inches"
)

## Annotate loops on Hi-C plot with squares
pixels <- annoPixels(
  plot = hicPlot, data = IMR90_DNAloops_pairs, type = "box"
)

```

In the output, only 2 loops are annotated instead of all loops present in the plot area. 

I love having the rectangle Hi-C plots as an option, though I know they are quite a hassle! Your time and effort are greatly appreciated!

**Comment by nekramer** [comment]
Thanks for finding this bug! I was able to find the problem and fix it in `plotHicRectangle` and `annoPixels`. Hope it works well for you now Sarah <3

Best,
Nicole
