### ISSUE TITLE
Rasterize

### ISSUE THREAD

**Issue by Zepeng-Mu** [PhanstielLab/plotgardener#73]
Hello,

I wonder whether it's possible to rasterize the signal tracks. I found it very slow to load and edit the PDF output in a vector graph editor.

Thanks

**Comment by nekramer** [comment]
Hi,

Rasterization would definitely be something great to add. Unfortunately, we don't have a built in option for this. However, I would recommend using the `rasterize` package. What you can do is save your plot to an object (i.e. `plotObject <- plotSignal()`) and then rasterize the grobs in that object with `grid.rasterize(plotObject$grobs$name)`. You can adjust the resolution of this rasterization as well and do this selectively for certain parts of your plot. I hope this helps!

Best,
Nicole

**Comment by nekramer** [comment]
Just wanted to check if this was able to work for you? Unless there are any other problems I will be closing this issue.

**Comment by Zepeng-Mu** [comment]
Sorry I haven't got time to test this, I hope to try plotgardener again for future projects.
