### ISSUE TITLE
plotGenes: knownGene to refGene

### ISSUE THREAD

**Issue by Kim-KL** [PhanstielLab/plotgardener#74]
Hi plotgardener,

I'd like to draw my gene track with "refGene", not "KnownGene". I want to use the same gene track with IGV (but w/ strand). I tried to load the library:TxDb.Hsapiens.UCSC.hg38.refGene and then use plotGenes. But it is not working. Can I change it? 

In addition, can I annotate the lncRNAs together?

Thanks a lot :) 
KL

**Comment by nekramer** [comment]
Hi KL,

If you want to use the refGene TxDb, you will have to update this with an `assembly` object in the `assembly` parameter of the `plotGenes` function like so: `plotGenes(assembly = assembly(Genome = "hg38refGene", TxDb = "TxDb.Hsapiens.UCSC.hg38.refGene", orgDb = "org.Hs.eg.db"))`. Within the `assembly` object you can also specify if you would like IDs or gene symbols to be displayed.

How are you trying to annotate lncRNAs?

Best,
Nicole

**Comment by Kim-KL** [comment]
Thanks for hg38, Nicole!

I'd like to add two lncRNAs(gtf and bed file formats) in plotGenes. But I don't know how to make hg38-based custom assembly for my lncRNAs. So, currently, I manually edit plot image to annotate my lncRNAs. Could you have any idea for this? 

Thank you so much!
KL

**Comment by nekramer** [comment]
Hi KL,

I would recommend making a custom TxDb from a comprehensive GTF file that includes all the gene annotations plus your lncRNA annotations (perhaps from GENCODE?). To make a custom TxDb from a GTF/GFF, you can use the function `makeTxDbFromGFF()` from the Bioconductor `GenomicFeatures` package. With this TxDb, you can construct your own `assembly` (you can see some documentation [here](https://phanstiellab.github.io/plotgardener/articles/guides/bioconductor_integration.html)), which you can pass into your `plotGenes` call. I'm not sure what kind of IDs you are working with here, but I would make sure to toggle those appropriately within the `gene.id.column` and `display.column` parameters of the `assembly()` function. Also just be aware that `plotGenes` will not be able to use any transcript identifiers.

If you run into any issues with GENCODE identifiers, I helped with a solution to this in issue #76 that you can refer to. I hope this helps annotate those lncRNAs!

Best,
Nicole

**Comment by Kim-KL** [comment]
I mixed refGene and ensembl GTFs. After setting gene.id.column and display.column to "ENSEMBL", it works very well. 
Thanks a lot, Nicole 👍 
-KL
