### ISSUE TITLE
Plotting gene tracks with GENCODE annotations

### ISSUE THREAD

**Issue by manuelfmerino** [PhanstielLab/plotgardener#76]
Hello,

I'm trying to plot some gene tracks using plotGenes. For the sake of robustness (I mapped some RNA-seq experiments using GENCODE annotations), I'm trying to create a custom txdb with the GTF file from GENCODE's latest release. 

From what I understood I must do, first I'm creating my custom txdb:

```
txdb_encode <- makeTxDbFromGFF("gencode.v42.annotation.gtf",
                               dataSource="GENCODE",
                               organism="Homo sapiens"
```

And then I'm preparing a custom assembly:

```
assembly_encode <- assembly("hg38_gencode_v42",
                            TxDb = txdb_encode,
                            OrgDb = "org.Hs.eg.db",
                            BSgenome = "BSgenome.Hsapiens.UCSC.hg38")
```

However, when I run plotGenes, specifying assembly = assembly_encode, I get the following message:

```
Error in .testForValidKeys(x, keys, keytype, fks) : 
  None of the keys entered are valid keys for 'ENTREZID'. Please use the keys method to see a listing of valid arguments.
```

I assume that this is because my annotation file GENEIDs is not in Entrez Gene format, but in GENCODE format instead. Since there is no GENCODE column in the org.Hs.eg.db OrgDb package that I am loading, I tried specifying gene.id.column="ENSEMBL", that uses an annotation almost identical to that in GENCODE, but the same problem arose.

I inspected some gene IDs in my GENCODE-derived txdb and noticed that they are not exactly identical to the ENSEMBL ones, because all of the id's end with an additional sequence (ie. ENSG00000290825 at ENSEMBL vs ENSG00000290825.1 at GENCODE). Is there any way I can modify the gene names in the txdb to match those in the OrgDb? I also saw that the TXNAME column in  my custom txdb matches the transcript names in the "UCSCKG" column in the OrgDb, maybe I can use the TXNAME values rather than the GENEID ones? Or maybe I should use a different OrgDb?

Thanks a lot,
Manuel F. Merino

**Comment by nekramer** [comment]
Hi Manuel,

The main reason `plotgardener` interfaces with orgDb packages is to get gene symbols, so if you are just trying to label genes with the GENCODE ID, I believe it will work to just set `gene.id.column` and `display.column` to `"ENSEMBL"`. If you would like to access gene symbols, it does get a bit trickier to mix and match the gene id keys from the GENCODE gtf and orgDb. To modify the gene names in the TxDb to match the OrgDb, I would recommend the following:
 1. Import the gtf as a GRanges object using `import.gff()` from `rtracklayer`
 2. Update the gene_id column to get rid of decimals after the ID: `gtf$gene_id <- gsub("\\..*", "", gtf$gene_id)`
 3. Make the TxDb from this GRanges object with `makeTxDbFromGRanges`
 4. Use this TxDb in the `plotgardener` `assembly` function and set `gene.id.column = "ENSEMBL"`.

I am not sure if this is the most elegant solution, but please let me know if this helps!

Best,
Nicole

**Comment by manuelfmerino** [comment]
Hi Nicole,

Worked like a charm, thanks a lot!

Best,
Manuel

**Comment by jeremymsimon** [comment]
Hi @nekramer! This workaround exactly as you describe works great in most instances, but there are a few edge cases where I get a `None of the keys entered are valid keys for 'ENSEMBL'. Please use the keys method to see a listing of valid arguments` error. I'm not sure if it's something specific to my GTF, or if this will simply happen for certain loci, but here's what I did:

```
hg38_gtf <- rtracklayer::import.gff("gencode.v43.annotation.gtf")
hg38_gtf$gene_id <- gsub("\\..*", "", hg38_gtf$gene_id)

hg38_gtf_txdb <- hg38_gtf %>% 
	set_genome_info(genome="hg38") %>%
	makeTxDbFromGRanges()

hg38_assembly <- assembly(
	Genome = "GENCODE_hg38",
	TxDb = hg38_gtf_txdb,
	OrgDb = "org.Hs.eg.db",
	gene.id.column = "ENSEMBL",
	BSgenome = "BSgenome.Hsapiens.UCSC.hg38"
)

[... plot tracks ...]

gene_plot <- plotGenes(
    params = params,
    assembly = hg38_assembly,
    y = "0.1b", height = 0.2,
    fontsize = 6
  )
``` 

An example set of coordinates that throws this error for me is
```
chr10 3747760 3767759
```

which at least in the UCSC Genome Browser shows a gene `ENSG00000229672` that may not have an annotated gene symbol, or perhaps it's not annotated in `org.Hs.eg.db` (?)

If I change my assembly to `assembly = "hg38"` I get no error, and for most other regions I've plotted this hasn't been an issue (and gene symbols display as expected)

Note this is with `plotgardener_1.6.4` - I can report my full sessionInfo if useful for debugging

Am I missing something here or is there another way around this?

Thanks!
Jeremy
