### ISSUE TITLE
readHic only support some special resolution

### ISSUE THREAD

**Issue by junjunlab** [PhanstielLab/plotgardener#78]
Hi, thanks for this great tool. I have a question that I am using **readHic** function that only support some special resolution resolution like 10000,50000 and 100000, the other values seem not be supported. Thanks!

**Comment by nekramer** [comment]
Thanks for checking out plotgardener! The resolutions that can be read in your .hic file by `readHic` are dependent on the initial processing of file itself. To see which resolutions your file contains after processing, you can use the `strawr` package function `readHicBpResolutions()`. Which tool(s) are you using to process your files? I may be able to refer you to additional documentation to process your data with the resolutions you need.

Best,
Nicole

**Comment by junjunlab** [comment]
Thanks for your help, I have understood it. Best wishes!
